version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o /dist/app /app/main.go" -command="/dist/app"
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
