version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: CompileDaemon -log-prefix=false -build="go build -o /dist/app /app/main.go" -command="/dist/app"
    ports:
      - 8080:8080
    # volumes:
    #   - ./server:/app # TODO - hot reload doesnt work rn
    networks:
      - backend
    environment:
      GAMESERVER_WEBSOCKET_URL: ws://localhost:8080/ws/v1/connect

networks:
  backend:
