version: "3.9"
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - backend
  game:
    build:
      context: server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
