name: kilnwood
gameserver:
  enabled: true
  name: kilnwood-gameserver
  host: kilnwood-game.com
  deploy:
    replicas: 1
    image: willcliffy/kilnwood
    tag: dev
  env:
    websocket_url: http://kilnwood-game.com/ws/v1/connect
