name: kilnwood
gameserver:
  enabled: true
  name: kilnwood-gameserver
  host: 
  deployment:
    replicas: 1
    image: willcliffy/kilnwood
    tag: dev
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "100m"
      memory: "100Mi"
