{{ if .Values.gameserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.gameserver.name }}-deploy"
  labels:
    app: "{{ .Values.gameserver.name }}"
spec:
  replicas: {{ .Values.gameserver.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.gameserver.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.gameserver.name }}"
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: "{{ .Values.gameserver.name }}"
        image: "{{ .Values.gameserver.deployment.image }}"
        imagePullPolicy: Always
        ports:
        - name: websocket
          containerPort: 9900
{{ end }}
