name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-client-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      if: success()
      run: |
        docker build client/ --file ./client/Dockerfile.dev -t willcliffy/kilnwood-client:$GITHUB_SHA -t willcliffy/kilnwood-client:latest -t willcliffy/kilnwood-client:dev
        docker push willcliffy/kilnwood-client:$GITHUB_SHA
        docker push willcliffy/kilnwood-client:dev
        docker push willcliffy/kilnwood-client:latest
  lint-gameserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --tests=false
          working-directory: server
  build-gameserver:
    runs-on: ubuntu-latest
    needs: lint-gameserver
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      if: success()
      run: |
        docker build server/ --file ./server/Dockerfile -t willcliffy/kilnwood:$GITHUB_SHA -t willcliffy/kilnwood:latest -t willcliffy/kilnwood:dev
        docker push willcliffy/kilnwood:$GITHUB_SHA
        docker push willcliffy/kilnwood:dev
        docker push willcliffy/kilnwood:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-gameserver
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: Install Helm
      if: success()
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: |-
        gcloud --quiet auth configure-docker
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
    - name: deploy
      run: helm upgrade --install kilnwood ./infra -f ./infra/values/dev.yaml --set gameserver.deploy.tag=$GITHUB_SHA --wait
