{{ if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.client.name }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
  labels:
    app: {{ .Values.client.name }}
spec:
  replicas: {{ .Values.client.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: {{ .Values.client.name }}
        image: "{{ .Values.client.deploy.image }}:{{ .Values.client.deploy.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
{{ end }}
